@startuml
title Diagramme de Séquence de connexion

actor Utilisateur
participant "Interface de Commande" as Interface
participant "Base de données" as BDD


Utilisateur -> Interface : Appuie sur le bouton de connexion
Interface -> Utilisateur : Affiche le formulaire de connexion

loop Tant que les identifiants sont incorrects
    Utilisateur -> Interface : Envoie les identifiants de connexion
    Interface -> BDD : Vérifie les identifiants
    activate BDD
    BDD --> Interface : Résultat (correct ou incorrect)
    deactivate BDD
    Interface -> Utilisateur : Message d'erreur si incorrect
end

alt Identifiants corrects
    Interface -> Utilisateur : Affiche la page index avec la liste des contacts
end

@enduml